In [2]:
v <- c(4, 8, 13, 18, 20)
print(v)

[1]  4  8 13 18 20


In [3]:
m <- matrix(1:6, nrow=2, ncol=3)
print(m)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [4]:
m[2, 3]

[1] 6

In [5]:
m[1, 2] <- 99
print(m)

     [,1] [,2] [,3]
[1,]    1   99    5
[2,]    2    4    6


In [8]:
a <- matrix(c(1, 2, 3, 4), nrow=2)
b <- matrix(c(2, 0, 1, 3), nrow=2)

result <- a %*% b
print(result)

     [,1] [,2]
[1,]    2   10
[2,]    4   14


In [9]:
a <- matrix(c(1, 2, 3, 4), nrow=2)
b <- matrix(c(2, 0, 2, 3), nrow=2)

result <- a %*% b
print(result)

     [,1] [,2]
[1,]    2   11
[2,]    4   16
